# Generated by Django 5.0.3 on 2024-09-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='descripcion',
            new_name='description',
        ),
    ]
